### ISSUE TITLE
Rendering issues at night races

### ISSUE THREAD

**Issue by DJfett** [virtual-programming/dirtshowdown-linux#12]
When racing in a nightly scenery, the graphics while racing are faulty. However this is not the case after the race ended, as when the scoreboard is shown. 

![2015-09-03_00002](https://cloud.githubusercontent.com/assets/1789521/9671254/d8a34776-5291-11e5-9415-243ebfe4948c.jpg)
![2015-09-03_00003](https://cloud.githubusercontent.com/assets/1789521/9671253/d89fb5ac-5291-11e5-9b43-b756f83be674.jpg)

```
Prozessor:
    Hersteller: GenuineIntel
    CPU-Familie: 0x6
    CPU-Modell: 0x3c
    CPU-Stepping: 0x3
    CPU-Typ: 0x0
    Geschwindigkeit: 4400 MHz
    4 logische Prozessoren
    4 technische Prozessoren
    HyperThreading:  Nicht unterstützt
    FCMOV:  Unterstützt
    SSE2:  Unterstützt
    SSE3:  Unterstützt
    SSSE3:  Unterstützt
    SSE4a:  Nicht unterstützt
    SSE41:  Unterstützt
    SSE42:  Unterstützt
    
Netzwerkinformationen:
    Netzwerk-Geschwindigkeit: 
    
Betriebssystem:
    Ubuntu 15.04 (64 Bit)
    Kernel-Name: Linux
    Kernel-Version: 4.0.0-040000-generic
    X-Server-Vendor: The X.Org Foundation
    X-Server-Release: 11701000
    X-Fenstermanager: Compiz
    Steam-Runtime-Version: steam-runtime-release_2015-06-12
    
Grafikkarte:
    Treiber: NVIDIA Corporation GeForce GTX 970/PCIe/SSE2

    Treiberversion: 4.5.0 NVIDIA 352.41
    OpenGL-Version: 4.5
    Desktop-Farbtiefe: 24 Bit per Pixel
    Monitor-Aktualisierungsrate: 60 Hz
    Anbieterkennung: 0x10de
    Gerätekennung: 0x13c2
    Anzahl der Monitore: 1
    Anzahl der logischen Grafikkarten: 1
    Prim. Anzeigeauflösung: 1920 x 1080
    Desktopauflösung: 1920 x 1080
    Prim. Anzeigegröße: 16,0 cm x 9,0 cm (18,3 cm diag.)

    Primärer Bus: PCI Express 16x
    Primärer VRAM: 4096 MB
    Unterstützte MSAA-Modi: 2x 4x 8x 16x 
    
Soundkarte:
    Audiogerät: Realtek ALC1150
    
Speicher:
    RAM: 15989 MB
    
Weitere Daten:
    UI-Sprache: Deutsch (Deutsch)
    SPRACHE: de_DE.UTF-8
    Mikrofon: Not set
    Verfügbarer Festplattenspeicher insgesamt: 938771 MB
    Größter freier Festplattenspeicherblock: 604780 MB
    
Installierte Software:
    
Neueste Fehlerberichte:
    Thu Sep  3 18:29:29 2015 GMT: file ''/tmp/dumps/assert_20150903202924_22.dmp'', upload yes: ''CrashID=bp-ebc8d7ca-ff65-488c-bb25-777d82150903''
```
